;       ---------------------------------------------------------
;       --             Adresses des registres sonores          --
;       ---------------------------------------------------------
ldff096         equ     D_ENDRAM-(8*28)
ldff09a         equ     ldff096+4
ldff0a0         equ     ldff09a+4
ldff0a8         equ     ldff0a0+12
ldff0b0         equ     ldff0a8+12
ldff0b8         equ     ldff0b0+12
ldff0c0         equ     ldff0b8+12
ldff0c8         equ     ldff0c0+12
ldff0d0         equ     ldff0c8+12
ldff0d8         equ     ldff0d0+12
ldff0e0         equ     ldff0d8+12
ldff0e8         equ     ldff0e0+12
ldff0f0         equ     ldff0e8+12
ldff0f8         equ     ldff0f0+12
ldff0g0         equ     ldff0f8+12
ldff0g8         equ     ldff0g0+12
ldff0h0         equ     ldff0g8+12
ldff0h8         equ     ldff0h0+12
