;	------------------------------------------------------------------------------
;	Title:programme test de g‚n‚ration code source
;
;	Copyright (c) Laurent FAVARD 1998
;	Code generated by JagStudio98 for DEVPAC 3, copyright FAVARD laurent 1996-1998
;
;	Business:Exercice de g‚n‚ration par JagStudio
;	------------------------------------------------------------------------------

		include		".\Include\sysapi.inc"
		include		".\Include\jag.inc"

		OUTPUT		program.Jag

		OPT	D-			; No debugging

		dc.b	'JAGR'			; Magic to skip Devpac Header
		dc.w	3			; JagOS 3 - Receive & Run
		dc.l	$5000			; Upload adress
		dc.l	C_End-C_Start		; Lenght of Jaguar Code
		dc.l	$5000			; Start address code


		TEXT
		Org		$5000


C_Start:
		pea.l		Welcome(pc)
		move.w		#DBMSG,-(sp)
		trap		#SYSTEM
		addq.l		#6,sp
;	------------------------------------------------------------------------------

		move.w		#EARTHEnd-EARTHBegin,-(sp)
		move.l		#EARTHBegin,-(sp)
		move.w		#SETICONPRG,-(sp)
		trap		#SYSTEM
		addq.l		#8,sp
;	------------------------------------------------------------------------------

		move.w		#APPLEEnd-APPLEBegin,-(sp)		; Lenght of packed datas
		move.l		#APPLEBegin,-(sp)		; Address of start packed datas
		move.w		#USER_MOUSE,-(sp)		; User define cursor
		move.w		#SETPOINTER,-(sp)
		trap		#SYSTEM
		addq.l		#4,sp
;	------------------------------------------------------------------------------

;	>>> Body program by user

Main:	

;	------------------------------------------------------------------------------

		pea.l		Goodbye(pc)
		move.w		#DBMSG,-(sp)
		trap		#SYSTEM
		addq.l		#6,sp
;	------------------------------------------------------------------------------

Pterm:	move.w		#PTERM,-(sp)
		trap		#SYSTEM
		illegal

;	------------------------------------------------------------------------------
		DATA
		EVEN
		; Icon program' datas
		include		".\Datas\EARTH.cci"

		DATA
		EVEN
		; Cursor program' datas
		include		".\Datas\APPLE.cci"

		DATA
		EVEN

Welcome:dc.b	"d‚but ex‚cution",0

		DATA
		EVEN

Goodbye:dc.b	"fin ex‚cution",0

;	------------------------------------------------------------------------------
C_End:
		END
