/* Indice du ressource pour SPEED__F */

#define MAINMENU 0   /* Arbre menu */
#define ABOUT    8   /* STRING dans l'arbre MAINMENU */
#define QUITTER  17  /* STRING dans l'arbre MAINMENU */

#define FMAIN    1   /* Formulaire/Dialogue */
#define B10KB    2   /* BUTTON dans l'arbre FMAIN */
#define B50KB    3   /* BUTTON dans l'arbre FMAIN */
#define B1KB     4   /* BUTTON dans l'arbre FMAIN */
#define RATE1    7   /* FBOXTEXT dans l'arbre FMAIN */
#define RATE2    8   /* FBOXTEXT dans l'arbre FMAIN */
#define RATE3    9   /* FBOXTEXT dans l'arbre FMAIN */
#define SEC1     10  /* FBOXTEXT dans l'arbre FMAIN */
#define SEC2     11  /* FBOXTEXT dans l'arbre FMAIN */
#define SEC3     12  /* FBOXTEXT dans l'arbre FMAIN */
#define JAG2ST   16  /* BUTTON dans l'arbre FMAIN */
#define ST2JAG   17  /* BUTTON dans l'arbre FMAIN */

#define FABOUT   2   /* Formulaire/Dialogue */

#define APPICON  3   /* Formulaire/Dialogue */
