/* Indice du ressource pour JAGROM_F */

#define MAINMENU 0   /* Arbre menu */
#define ITEM41   6   /* TITLE dans l'arbre MAINMENU */
#define ITEM11   9   /* STRING dans l'arbre MAINMENU */
#define ITEM21   18  /* STRING dans l'arbre MAINMENU */
#define ITEM22   20  /* STRING dans l'arbre MAINMENU */
#define ITEM31   22  /* STRING dans l'arbre MAINMENU */
#define ITEM32   23  /* STRING dans l'arbre MAINMENU */

#define FMAIN    1   /* Formulaire/Dialogue */
#define FILEINFO 2   /* BOXTEXT dans l'arbre FMAIN */
#define BJAUGE   3   /* BOX dans l'arbre FMAIN */
#define JAUGE    4   /* BOX dans l'arbre FMAIN */
#define TIME     5   /* FTEXT dans l'arbre FMAIN */
#define RATE     6   /* FTEXT dans l'arbre FMAIN */
#define QUIT     7   /* BUTTON dans l'arbre FMAIN */
#define SELECT   9   /* BUTTON dans l'arbre FMAIN */
#define UPLOAD   10  /* BUTTON dans l'arbre FMAIN */
#define MAKE     11  /* BUTTON dans l'arbre FMAIN */
#define JGON     12  /* BUTTON dans l'arbre FMAIN */

#define FABOUT   2   /* Formulaire/Dialogue */

#define APPICON  3   /* Formulaire/Dialogue */
