;       ---------------------------------------------------------
;       --             Adresses des registres sonores          --
;       ---------------------------------------------------------
ldff096         equ     D_ENDRAM-(4*28)
ldff09a         equ     ldff096+4
ldff0a0         equ     ldff09a+4
ldff0a8         equ     ldff0a0+12
ldff0b0         equ     ldff0a8+12
ldff0b8         equ     ldff0b0+12
ldff0c0         equ     ldff0b8+12
ldff0c8         equ     ldff0c0+12
ldff0d0         equ     ldff0c8+12
ldff0d8         equ     ldff0d0+12

